- client/shared/base_syncdata.py
Add clean session if failed to receive the package
cause socket timeout or NetCommunication error.
Signed-off-by: Shuping Cui <scui@redhat.com>
> client.shared: Improve _recv_data function

- contrib/install-autotest-server.sh
- frontend/pkgdeps.py
This is a follow up to #909.
Add installation support for Red Hat Enterprise Linux 7.1
This series of patches cleans up the use of the print_log procedure, refactors the human-readable database package name, and finally, refactors the installation procedure into one for debian, one for fedora, and a common utility function for both.
With these changes I am able to run the autotest installation procedure on RHEL-7.1 and get a working configuration.
Signed-off-by: Jeff E. Nelson <jnmnus@yahoo.com>
> [V2] RHEL 7 support

- client/shared/openvswitch.py
Fix #910
With this, we'll be able to handle versions like
2.3.1-git3282e51 correctly.
Signed-off-by: Lucas Meneghel Rodrigues <lmr@redhat.com>
> client.shared.openvswitch: Fix version parsing

- client/shared/distro_def.py
Which doesn't seem to exist anymore and is causing CI failures.
Signed-off-by: Cleber Rosa <crosa@redhat.com>
> client/shared/distro_def.py: Remove pylint W0142

- setup.py
- shared/common.py
- shared/setup.py
That module is used for definitions that are common to both autotest
(RPC) server and clients.
Signed-off-by: Cleber Rosa <crosa@redhat.com>
> setup.py: include a setup module for shared module

- client/shared/git.py
When setting to fetch from a remote branch different than master, the
local repository is not enable to checkout to the branch due to hardcode
name 'master' used to setup the local branch name.
This patch changes the default name of lbranch variables from 'master'
to be None, and then setup in code the value to be the same of remote
branch name, usually specified by user and as already explained in
documentation.
Signed-off-by: Paulo Vital <paulo.vital@profitbricks.com>
> Fix git issue with branch different than master.

- client/shared/utils.py
hugetlbfs should be treated as same as 'nfs', 'smbfs'
and 'glusterfs'.
> client/shared/utils.py: Add hugetlbfs for is_mounted()

- client/shared/service_unittest.py
TestSystemdServiceManager aims to verify _SystemdServiceManager,and
TestSysVInitServiceManager corresponding to _SysVInitServiceManager.
Both _SystemdServiceManager and _SysVInitServiceManager inherits
from _GenericServiceManager.
so let the test module in accordance with the hierarchy.
> service_unittest: meet OOD-principle and the hierarchy

- utils/test_importer.py
The variable full_path is unused,
so the statement used to evaluate it becomes meaningless.
> utils/test_importer: remove meaningless statement

- CODING_STYLE
- README.rst
* CODING_STYLE: s/Readbility/Readability/g
* README.rst  : delete the surplus letter 'a'
> Manual: fix typo

- client/shared/iso9660.py
As /proc/filesystems only show the supported file system by running
kernel. So iso9660 will not show up if no cdrom or iso is already
mounted. So use kallsyms instead of this file to check it.
> autotest.client.shared: Update the kernel support check method

- client/os_dep.py
- client/os_dep_unittest.py
Rewrite commands, libraries and headers to use common searching functions.
The lib searcher was re-implemented to match as close as possible the C
ldconfig implementation.  The C source code was translated line-by-line
as close as possible into python, so we preserve the exact same
behaviour with regards to recurrsion.
Unittests included to check all the interesting corner cases.
Also try to match `which` behaviour as close as possible.
Disabled pytest specific unittests.
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>
> os_dep: refactor into common functions

- client/shared/distro.py
/etc/SuSE-release is a file with format:
SUSE Linux Enterprise Server NN (arch)
VERSION = <major release>
PATCHLEVEL = <service pack #>
Signed-off-by: Nishanth Aravamudan <nacc@linux.vnet.ibm.com>
> client/shared/distro: add probe for SUSE based distributions

- client/shared/iso9660.py
When the iso9660 module is not loaded, the "/proc/kallsyms" doesn't list
it. This patch executes modprobe first.
Additionally it replaces the "/proc/kallsyms" with "/proc/filesystems"
which is recommended for supported filesystem checks.
Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>
> client.shared.iso9660: Insert module before check

- scheduler/host_scheduler.py
- scheduler/scheduler_models.py
Consider having a host reserved in Autotest with label 'L'. Run a
job-by-label (metahost) for 1 label-'L' host. The current scheduler will
not exclude your reserved host from the set of possible hosts to run the
metahost job on, because it only checks that your user has permission to
run on candidate hosts, not if those candidate hosts are already in-use.
I'm assuming that reservations in Autotest are specifically intended to
indicate a host is "in-use". I think this is the principle of least
surprise for reservations. With the changes in this commit, candidate
hosts' ACLs are checked against the "Everyone" ACL for set-identity and
excluded if there is an ACL in place.
Signed-off-by: Nishanth Aravamudan <nacc@linux.vnet.ibm.com>
> scheduler: fix corner case with metahost scheduling on reserved hosts

- client/autotest_local.py
Fix the problem that CUSTOM_DIR is assigned after
cmdparser uses it.
Signed-off-by: Aska.Wu <aska.wu@acer.com>
> autotest-local: Fix test directory usage

- frontend/client/src/autotest/afe/HostSelector.java
- frontend/client/src/autotest/afe/JobDetailView.java
When attempting to test a one-time host, I noticed installation was attempted, because we aren't specifying a N/A profile on submit.
> Host Selector fix

- frontend/urls.py
It throws a 404, because there is no reference to new_tko/admin.
Signed-off-by: Nishanth Aravamudan <nacc@linux.vnet.ibm.com>
> frontend: fix new_tko admin link

- server/base_utils.py
With profile support, there is an additional special character ('#') in
machine names.
Signed-off-by: Nishanth Aravamudan <nacc@linux.vnet.ibm.com>
> base_utils/parse_machine: fix comment

- utils/external_packages.py
Use GWT 2.7.0 instead of 2.5.1.
Signed-off-by: Lucas Meneghel Rodrigues <lmr@redhat.com>
> utils.external_packages: Update GWT to 2.7.0

- frontend/client/src/autotest/afe/HostDataSource.java
Add a missing string identifier to HostDataSource, fixing
a compilation bug added with commit 0bc0c0b7.
Signed-off-by: Lucas Meneghel Rodrigues <lmr@redhat.com>
> frontend/HostDataSource.java: Add HostDataSource string identifier

- documentation/source/main/remote/Autoserv.rst
Replaced ./autoserv with ./autotest-remote. 
In latest source code, autoserv is not executable python file. 
Reference: https://github.com/autotest/autotest/issues/980
> ./autoserv in invalid

- client/tools/results2junit.py
Fixes #984
Sometimes when a job fails in a particular way, this conversion script
dies where it should just report the particular test as failed. Fix
the script by being more careful on whether it could actually read
from the test debug file and handling each situation accordingly.
Signed-off-by: Lucas Meneghel Rodrigues <lookkas@gmail.com>
Signed-off-by: Chris Evich <cevich@redhat.com>
> ults2junit.py: More robust for unreadable files

- client/harness_beaker.py
- client/shared/mock.py
- client/shared/test_utils/mock.py
- client/shared/utils.py
- frontend/afe/resources.py
- frontend/shared/resource_lib.py
- frontend/shared/rest_client.py
- utils/external_packages.py
This pull request is focused on fixing the E1136 errors enabled in the latest pylint/inspektor. It contains two actual bugfixes, the rest only handles false-negatives.
> Fix pylint E1136 errors

- .travis.yml
According to https://github.com/travis-ci/travis-ci/issues/5221, it's
necessary (temporarily?) to do an `apt-get update` before attempting
to install packages using `apg-get install`.
Signed-off-by: Cleber Rosa <crosa@redhat.com>
> Travis CI: workaround bug on GCE machines

- setup.py
The build_doc command allows the Sphinx based documentation to be built
right from setup.py. But, since it's not essential to Autotest performing
its due functions, let's make the command, and the requirement optional.
Signed-off-by: Cleber Rosa <crosa@redhat.com>
> setup.py: make Sphinx dependency optional

- frontend/client/src/autotest/public/TkoClient.html
Admin link was throwing 404 as it was pointing to wrong url
> Fix broken link to admin page

- client/shared/utils.py
ubifs should be treated as nfs, smbfs and so on because 'src' may be 
something like "ubi0_0", "ubi0:volumename" and so on
> client/shared/utils.py: add ubifs support

- client/setup.py
Installation aborted with following error on RHEL distributions,
so made this patch to fix it.
> error: can't copy 'client/deps/grubby': doesn't exist or not a regular file
> client.setup: fix installation issue

- client/base_utils.py
Total number of host cpus not always matches
cpuinfo output (e:g:- power8 ppc arch).
This patch addresses the same by taking total cpus
from sysfs(/sys/devices/system/cpu/present) and
fallback incase of the file not found to the old method.
> Fixup: Count cpus in host

- client/base_utils.py
it is defined in glibc so it will do the right thing
Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>
> use SC_NPROCESSORS_ONLN to find number of online processors

- utils/unittest_suite_nose.py
Add an option (--autotest-skip-dirs) in the unittest_suite_nose.py
script to allow for skipping certain directories of tests. This can
be used, for example, to silence test failiures in 3rd party libraries
for which the environment is not set up appropriately.
Signed-off-by: Vignesh Varadarajan <vigneshv@oc6571381235.ibm.com>
> Add option --autotest-skip-dirs to unittest_suite_nose.py

- client/shared/base_check_version.py
Setup: Fedora 26 ships with pylint-3 as default:
lrwxrwxrwx. 1 root root 10 Aug  2 11:57 /usr/bin/pylint -> pylint-3.6
This triggers autotest to look for python2.x and restart, but
the glob that's looked for is 'python2*' (not 'python2.*') and
extract_version() can't recognize plain 'python2'. Accept that
and just move along.
Signed-off-by: Ed Santiago <santiago@redhat.com>
> find_desired_python: cope with empty version

- client/setup.py
- client/shared/settings.py
When running autotest from venv we should be using sys.prefix as top
directory instead of /etc/autotest, unless user sets the
AUTOTEST_TOP_PATH.
Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>
> setup/settings: Support venv to get top autotest path

- client/tools/JUnit_api.py
Possibly hit UnicodeDecodeError exception when use tools/results2junit.py
to covert test result to junit format xml and failed to generate it.
The patch tries to catch it and does not interrupt generate process.
Error message example:
UnicodeDecodeError: 'ascii' codec can't decode byte 0x94 in position 28701:
ordinal not in range(128)
Signed-off-by: Xiao Liang <xiliang@redhat.com>
> tools/JUnit_api: handle exceptions while doing str encode

- MANIFEST.in
- client/setup.py
- client/shared/settings.py
- setup.py
In linux world the configs are most commonly stored in "/etc", but in
purely python world they are "resources" as every other asset. Let's
change the way we discover the locations of those file to respect the
python defaults while still prioritizing the "/etc" as was before for
compatibility reasons.
This should suit most cases as distribution packages (RPM) can put the
config files in /etc but "python setup.py install" will use the
"resource" path (usually /usr/lib/python2.7/...) while still respecting
the /etc if created manually by users.
This is needed to avoid creating files in "/etc", which is not allowed
in easy_install or in non-priviledged mode.
Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>
> client.shared.settings: Cope with standard python config locations

- client/shared/version.py
Most callers require the version info to be of the form
12.34.56, so testing it against None is not enough if ever
'git describe' returns anything else.
> Use more robust version info through stricter test

- client/base_utils.py
- client/kvm_control.py
- client/kvm_control_unittest.py
Add Hygon CPU Vendor ID checking in get_cpu_vendor_name and return hygon
add kvm arch support for Hygon reuse kvm_amd as Hygon Dhyana(Family 18h) share similiar arch with AMD Family 17h, and add related unittest.
> add Hygon Dhyana support for get_cpu_vendor_name and support kvm arch

- client/job.py
- contrib/coverage.py
- mirror/mirror
- server/server_job.py
Built-in function execfile has been removed in python3.0
Use open, read and exec instead.
[1] https://docs.python.org/3.0/whatsnew/3.0.html?highlight=execfile#builtins
Signed-off-by: Po-Hsu Lin \<po-hsu.lin@canonical.com\>
> Fix execfile() after python3.0

- client/shared/distro.py
- client/tools/boottool.py
platform.dist() deprecated since 3.5 [1]
Use distro module instead.
[1] https://docs.python.org/3.7/library/platform.html#unix-platforms
Signed-off-by: Po-Hsu Lin \<po-hsu.lin@canonical.com\>
> Fix platform.dist() after python3.5

- client/shared/jsontemplate.py
- frontend/afe/views.py
cgi.escape has been deprecated since 3.2 [1]
Use html.escape instead.
[1] https://docs.python.org/3.5/library/cgi.html
Signed-off-by: Po-Hsu Lin \<po-hsu.lin@canonical.com\>
> Fix cgi.escape after python3.2

- client/tools/results2junit.py
If the text is None, the replace will cause AttributeError.
Make sure it's not None before trying to modify it.
Signed-off-by: Po-Hsu Lin \<po-hsu.lin@canonical.com\>
> results2junit.py: Make sure text is not none before trying to modify it

- client/base_utils.py
- client/shared/base_packages.py
- client/shared/iso9660.py
- client/shared/progressbar.py
- client/shared/utils.py
- client/tools/JUnit_api.py
- documentation/source/main/developer/SubmissionChecklist.rst
- documentation/source/main/developer/Tests/TestCodingStyle.rst
- documentation/source/main/local/DistroDetection.rst
- documentation/source/main/remote/Conmux-OriginalDocumentation.rst
- documentation/source/main/sysadmin/PackagingExample.rst
- server/frontend.py
There are small typos in:
- client/base_utils.py
- client/shared/base_packages.py
- client/shared/iso9660.py
- client/shared/progressbar.py
- client/shared/utils.py
- client/tools/JUnit_api.py
- documentation/source/main/developer/SubmissionChecklist.rst
- documentation/source/main/developer/Tests/TestCodingStyle.rst
- documentation/source/main/local/DistroDetection.rst
- documentation/source/main/remote/Conmux-OriginalDocumentation.rst
- documentation/source/main/sysadmin/PackagingExample.rst
- server/frontend.py
Fixes:
- Should read `preferable` rather than `preferrable`.
- Should read `minimum` rather than `mininum`.
- Should read `successfully` rather than `successfuly`.
- Should read `sophisticated` rather than `sophisiticated`.
- Should read `smoothly` rather than `smootlhy`.
- …
> docs: fix a few simple typos
